# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.CharField(max_length=5000)),
                ('auteur', models.CharField(max_length=50, verbose_name='publi\xe9 par')),
                ('pub_date', models.DateTimeField(verbose_name='publi\xe9 le')),
                ('edit_date', models.DateTimeField(verbose_name='modifi\xe9 le')),
            ],
        ),
    ]
