# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteTF2', '0002_auto_20160505_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='postaccueil',
            name='contenu',
            field=models.CharField(max_length=10000),
        ),
    ]
